	protected TapMagic magic;
	protected TapOpcode opcode;
	protected short keylength;
	protected byte extralength;
	protected byte datatype;
	protected short vbucket;
	protected int totalbody;
	protected int opaque;
	protected long cas;
