import org.eclipse.jface.widgets.TestUnitButtonFactory;
import org.eclipse.jface.widgets.TestUnitCompositeFactory;
import org.eclipse.jface.widgets.TestUnitControlFactory;
import org.eclipse.jface.widgets.TestUnitItemFactory;
import org.eclipse.jface.widgets.TestUnitLabelFactory;
import org.eclipse.jface.widgets.TestUnitSpinnerFactory;
import org.eclipse.jface.widgets.TestUnitTableColumnFactory;
import org.eclipse.jface.widgets.TestUnitTableFactory;
import org.eclipse.jface.widgets.TestUnitTextFactory;
