	PropertyShowInContextTest.class,
	MultiInstancePropertySheetTest.class,
	ShowInPropertySheetTest.class,
	NewPropertySheetHandlerTest.class,
	PropertySheetAuto.class,
	ComboBoxPropertyDescriptorTest.class,
	DirtyStatePropertySheetTest.class,
