	public static final int LIFECYCLE_AWARE = 6;

	public static final int LIFECYCLE_AWARE__LIFE_CYCLE_HANDLERS = 0;

	public static final int LIFECYCLE_AWARE_FEATURE_COUNT = 1;

	public static final int LIFECYCLE_AWARE_OPERATION_COUNT = 0;

	public static final int LIFECYCLE_CONTRIBUTION = 7;

	public static final int LIFECYCLE_CONTRIBUTION__ELEMENT_ID = CONTRIBUTION__ELEMENT_ID;

	public static final int LIFECYCLE_CONTRIBUTION__PERSISTED_STATE = CONTRIBUTION__PERSISTED_STATE;

	public static final int LIFECYCLE_CONTRIBUTION__TAGS = CONTRIBUTION__TAGS;

	public static final int LIFECYCLE_CONTRIBUTION__CONTRIBUTOR_URI = CONTRIBUTION__CONTRIBUTOR_URI;

	public static final int LIFECYCLE_CONTRIBUTION__TRANSIENT_DATA = CONTRIBUTION__TRANSIENT_DATA;

	public static final int LIFECYCLE_CONTRIBUTION__CONTRIBUTION_URI = CONTRIBUTION__CONTRIBUTION_URI;

	public static final int LIFECYCLE_CONTRIBUTION__OBJECT = CONTRIBUTION__OBJECT;

	public static final int LIFECYCLE_CONTRIBUTION_FEATURE_COUNT = CONTRIBUTION_FEATURE_COUNT + 0;

	public static final int LIFECYCLE_CONTRIBUTION_OPERATION_COUNT = CONTRIBUTION_OPERATION_COUNT + 0;

