		keyCodes.put("BACKSPACE", Integer.valueOf(8)); //$NON-NLS-1$
		keyCodes.put("TAB", Integer.valueOf(9)); //$NON-NLS-1$
		keyCodes.put("RETURN", Integer.valueOf(13)); //$NON-NLS-1$
		keyCodes.put("ENTER", Integer.valueOf(13)); //$NON-NLS-1$
		keyCodes.put("ESCAPE", Integer.valueOf(27)); //$NON-NLS-1$
		keyCodes.put("ESC", Integer.valueOf(27)); //$NON-NLS-1$
		keyCodes.put("DELETE", Integer.valueOf(127)); //$NON-NLS-1$

		keyCodes.put("SPACE", Integer.valueOf(' ')); //$NON-NLS-1$
		keyCodes.put("ARROW_UP", Integer.valueOf(SWT.ARROW_UP)); //$NON-NLS-1$
		keyCodes.put("ARROW_DOWN", Integer.valueOf(SWT.ARROW_DOWN)); //$NON-NLS-1$
		keyCodes.put("ARROW_LEFT", Integer.valueOf(SWT.ARROW_LEFT)); //$NON-NLS-1$
		keyCodes.put("ARROW_RIGHT", Integer.valueOf(SWT.ARROW_RIGHT)); //$NON-NLS-1$
		keyCodes.put("PAGE_UP", Integer.valueOf(SWT.PAGE_UP)); //$NON-NLS-1$
		keyCodes.put("PAGE_DOWN", Integer.valueOf(SWT.PAGE_DOWN)); //$NON-NLS-1$
		keyCodes.put("HOME", Integer.valueOf(SWT.HOME)); //$NON-NLS-1$
		keyCodes.put("END", Integer.valueOf(SWT.END)); //$NON-NLS-1$
		keyCodes.put("INSERT", Integer.valueOf(SWT.INSERT)); //$NON-NLS-1$
		keyCodes.put("F1", Integer.valueOf(SWT.F1)); //$NON-NLS-1$
		keyCodes.put("F2", Integer.valueOf(SWT.F2)); //$NON-NLS-1$
		keyCodes.put("F3", Integer.valueOf(SWT.F3)); //$NON-NLS-1$
		keyCodes.put("F4", Integer.valueOf(SWT.F4)); //$NON-NLS-1$
		keyCodes.put("F5", Integer.valueOf(SWT.F5)); //$NON-NLS-1$
		keyCodes.put("F6", Integer.valueOf(SWT.F6)); //$NON-NLS-1$
		keyCodes.put("F7", Integer.valueOf(SWT.F7)); //$NON-NLS-1$
		keyCodes.put("F8", Integer.valueOf(SWT.F8)); //$NON-NLS-1$
		keyCodes.put("F9", Integer.valueOf(SWT.F9)); //$NON-NLS-1$
		keyCodes.put("F10", Integer.valueOf(SWT.F10)); //$NON-NLS-1$
		keyCodes.put("F11", Integer.valueOf(SWT.F11)); //$NON-NLS-1$
		keyCodes.put("F12", Integer.valueOf(SWT.F12)); //$NON-NLS-1$
		keyCodes.put("F13", Integer.valueOf(SWT.F13)); //$NON-NLS-1$
		keyCodes.put("F14", Integer.valueOf(SWT.F14)); //$NON-NLS-1$
		keyCodes.put("F15", Integer.valueOf(SWT.F15)); //$NON-NLS-1$
		keyCodes.put("F16", Integer.valueOf(SWT.F16)); //$NON-NLS-1$
		keyCodes.put("F17", Integer.valueOf(SWT.F17)); //$NON-NLS-1$
		keyCodes.put("F18", Integer.valueOf(SWT.F18)); //$NON-NLS-1$
		keyCodes.put("F19", Integer.valueOf(SWT.F19)); //$NON-NLS-1$
		keyCodes.put("F20", Integer.valueOf(SWT.F20)); //$NON-NLS-1$
