		g1 = createEGenericType(theUiPackage.getElementContainer());
		g2 = createEGenericType(this.getFrameElement());
		g1.getETypeArguments().add(g2);
		frameEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(theUiPackage.getUILabel());
		frameEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(theUiPackage.getContext());
		frameEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(theCommandsPackage.getHandlerContainer());
		frameEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(theCommandsPackage.getBindings());
		frameEClass.getEGenericSuperTypes().add(g1);
		frameElementEClass.getESuperTypes().add(theUiPackage.getUIElement());
		g1 = createEGenericType(theUiPackage.getUILabel());
		dialogEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(theUiPackage.getGenericTile());
		g2 = createEGenericType(this.getPartSashContainerElement());
		g1.getETypeArguments().add(g2);
		dialogEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(this.getFrameElement());
		dialogEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(theUiPackage.getUILabel());
		wizardEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(theUiPackage.getGenericStack());
		g2 = createEGenericType(this.getStackElement());
		g1.getETypeArguments().add(g2);
		wizardEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(this.getFrameElement());
		wizardEClass.getEGenericSuperTypes().add(g1);
