@SuiteClasses({ AggregateValidationStatusTest.class, BindingTest.class, DatabindingContextTest.class,
		ListBindingTest.class, UpdateStrategyTest.class, UpdateListStrategyTest.class, UpdateSetStrategyTest.class,
		UpdateValueStrategyTest.class, ValueBindingTest.class, ObservablesManagerTest.class, PolicyTest.class,
		AnonymousBeanValuePropertyTest.class, AnonymousPojoValuePropertyTest.class, BeanPropertiesTest.class,
		BeansObservablesTest.class, PojoObservablesTest.class, PojoPropertiesTest.class, SetOnlyJavaBeanTest.class,
		NumberToStringConverterTest.class, StringToNumberConverterTest.class, AbstractObservableTest.class,
		ChangeSupportTest.class, DecoratingObservableTest.class, Diffs_ListDiffTests.class, DiffsTest.class,
		ObservablesTest.class, ObservableTrackerTest.class, RealmTest.class, AbstractObservableListTest.class,
		ComputedListTest.class, DecoratingObservableListTest.class, ListDiffTest.class, ListDiffVisitorTest.class,
		MultiListTest.class, ObservableListTest.class, WritableListTest.class, AbstractObservableMapTest.class,
		BidiObservableMapTest.class, ObservableMapTest.class, WritableMapTest.class, CompositeMapTest.class,
		ComputedObservableMapTest.class, AbstractObservableSetTest.class, ComputedSetTest.class,
		DecoratingObservableSetTest.class, ObservableSetTest.class, UnionSetTest.class, WritableSetTest.class,
		AbstractObservableValueTest.class, AbstractVetoableValueTest.class, ComputedValueTest.class,
		DateAndTimeObservableValueTest.class, DecoratingObservableValueTest.class, DuplexingObservableValueTest.class,
		SelectObservableValueTest.class, WritableValueTest.class, MultiValidatorTest.class, ValidationStatusTest.class,
		BindingMessagesTest.class, BindingStatusTest.class, ConverterValuePropertyTest.class,
		DifferentRealmsBindingTest.class, IdentityMapTest.class, IdentitySetTest.class, QueueTest.class,
		DateConversionSupportTest.class, IdentityConverterTest.class, IntegerToStringConverterTest.class,
		NumberToBigDecimalTest.class, NumberToBigIntegerConverterTest.class, NumberToByteConverterTest.class,
		NumberToDoubleConverterTest.class, NumberToFloatConverterTest.class, NumberToIntegerConverterTest.class,
		NumberToLongConverterTest.class, NumberToShortConverterTest.class, ObjectToPrimitiveValidatorTest.class,
		StatusToStringConverterTest.class, StringToBooleanConverterTest.class, StringToByteConverterTest.class,
		StringToCharacterConverterTest.class, StringToNumberParserByteTest.class, StringToNumberParserDoubleTest.class,
		StringToNumberParserFloatTest.class, StringToNumberParserIntegerTest.class, StringToNumberParserLongTest.class,
		StringToNumberParserShortTest.class, StringToNumberParserTest.class, StringToShortConverterTest.class,
		BeanObservableListDecoratorTest.class, BeanObservableSetDecoratorTest.class,
		BeanObservableValueDecoratorTest.class, BeanObservableListDecoratorTest.class, BeanValuePropertyTest.class,
		JavaBeanObservableArrayBasedListTest.class, JavaBeanObservableArrayBasedSetTest.class,
		JavaBeanObservableListTest.class, JavaBeanObservableMapTest.class, JavaBeanObservableSetTest.class,
		JavaBeanObservableValueTest.class, JavaBeanPropertyObservableMapTest.class, BeanPropertyHelperTest.class,
		BeanPropertyListenerSupportTest.class, BeanPropertyListenerTest.class, ConstantObservableValueTest.class,
		DelayedObservableValueTest.class, EmptyObservableListTest.class, EmptyObservableSetTest.class,
		IdentityObservableSetTest.class, MapEntryObservableValueTest.class, StalenessObservableValueTest.class,
		UnmodifiableObservableValueTest.class, UnmodifiableObservableListTest.class,
		UnmodifiableObservableSetTest.class, ValidatedObservableValueTest.class, ValidatedObservableListTest.class,
		ValidatedObservableSetTest.class, DetailObservableListTest.class, DetailObservableMapTest.class,
		DetailObservableSetTest.class, DetailObservableValueTest.class, ListDetailValueObservableListTest.class,
		MapDetailValueObservableMapTest.class, SetDetailValueObservableMapTest.class,
		MapSimpleValueObservableMapTest.class, SetSimpleValueObservableMapTest.class,
		ListSimpleValueObservableListTest.class, AbstractStringToNumberValidatorTest.class,
		NumberToByteValidatorTest.class, NumberToDoubleValidatorTest.class, NumberToFloatValidatorTest.class,
		NumberToIntegerValidatorTest.class, NumberToLongValidatorTest.class, NumberToShortValidatorTest.class,
		NumberToUnboundedNumberValidatorTest.class, StringToByteValidatorTest.class,
		StringToCharacterValidatorTest.class, StringToDoubleValidatorTest.class, StringToFloatValidatorTest.class,
		StringToIntegerValidatorTest.class, StringToLongValidatorTest.class, StringToShortValidatorTest.class,
		BindingScenariosTestSuite.class, SWTObservablesTest.class, WidgetPropertiesTest.class,
		WidgetObservableThreadTest.class, PreferencePageSupportTest.class, ObservableListContentProviderTest.class,
		ObservableListTreeContentProviderTest.class, ObservableMapLabelProviderTest.class,
		ObservableSetContentProviderTest.class, ObservableSetTreeContentProviderTest.class,
		ObservableValueEditingSupportTest.class, ViewersObservablesTest.class, ViewerSupportTest.class,
		WizardPageSupportTest.class, EditMaskLexerAndTokenTest.class, EditMaskParserTest.class,
		ButtonObservableValueTest.class, CComboObservableValueTest.class, CComboObservableValueSelectionTest.class,
		CComboObservableValueTextTest.class, CComboSingleSelectionObservableValueTest.class,
		CComboSingleSelectionObservableValueTest.class, CLabelObservableValueTest.class, ComboObservableValueTest.class,
		ComboObservableValueSelectionTest.class, ComboObservableValueTextTest.class,
		ComboSingleSelectionObservableValueTest.class, DateTimeCalendarObservableValueTest.class,
		DateTimeDateObservableValueTest.class, DateTimeSelectionPropertyTest.class,
		DateTimeTimeObservableValueTest.class, SWTDelayedObservableValueDecoratorTest.class,
		ControlObservableValueTest.class, LabelObservableValueTest.class, GroupObservableValueTest.class,
		ListSingleSelectionObservableValueTest.class, ScaleObservableValueMinTest.class,
		ScaleObservableValueMaxTest.class, ScaleObservableValueSelectionTest.class, ShellObservableValueTest.class,
		SpinnerObservableValueTest.class, SpinnerObservableValueMinTest.class, SpinnerObservableValueMaxTest.class,
		SpinnerObservableValueSelectionTest.class, TableObservableValueTest.class,
		TableSingleSelectionObservableValueTest.class, TextEditableObservableValueTest.class,
		TextObservableValueDefaultSelectionTest.class, TextObservableValueFocusOutTest.class,
		TextObservableValueModifyTest.class, TextObservableValueTest.class,
		StyledTextObservableValueDefaultSelectionTest.class, StyledTextObservableValueFocusOutTest.class,
		StyledTextObservableValueModifyTest.class, StyledTextObservableValueTest.class,
		CheckableCheckedElementsObservableSetTest.class, ObservableViewerElementSetTest.class,
		ObservableCollectionContentProviderTest.class, ObservableCollectionTreeContentProviderTest.class,
		SelectionProviderMultiSelectionObservableListTest.class,
		SelectionProviderSingleSelectionObservableValueTest.class, ViewerElementMapTest.class,
		ViewerElementSetTest.class, ViewerElementWrapperTest.class, ViewerInputObservableValueTest.class,
		BindingTestSuiteJunit3.class })
