 * In order to successfully run this test you must create a Membase bucket
 * on your server named "bucket", with password "password". The bucket must
 * also be empty. Having keys not generated by this test in you bucket can
 * cause this test to fail.
 *
 * This test tests that a tap stream is capable of connecting to a named
 * bucket and functions properly. The test puts 500 items into the bucket
 * and then checks to see that they are all streamed out of the bucket by
 * using a tap backfill stream.
