 * [*] --> Disconnected
 * Disconnected --> Connecting
 * Connecting --> Disconnected
 * Connecting --> Connected
 * Connecting --> Degraded
 * Connected --> Disconnecting
 * Connected --> Degraded
 * Degraded --> Connected
 * Disconnecting -> Disconnected
