  private static final String BUCKETS_STRING =
      "[\n"
          + "    {\n"
          + "        \"authType\": \"sasl\", \n"
          + "        \"basicStats\": {\n"
          + "            \"diskFetches\": 0, \n"
          + "            \"diskUsed\": 2912256, \n"
          + "            \"itemCount\": 0, \n"
          + "            \"memUsed\": 26001976, \n"
          + "            \"opsPerSec\": 0, \n"
          + "            \"quotaPercentUsed\": 24.797416687011719\n"
          + "        }, \n"
          + "        \"bucketType\": \"membase\", \n"
          + "        \"flushCacheUri\": \"/pools/default/buckets/default/"
          + "controller/doFlush\", \n"
          + "        \"name\": \"default\", \n"
          + "        \"nodeLocator\": \"vbucket\", \n"
          + "        \"nodes\": [\n"
          + "            {\n"
          + "                \"clusterCompatibility\": 1, \n"
          + "                \"clusterMembership\": \"active\", \n"
          + "                \"hostname\": \"127.0.0.1:8091\", \n"
          + "                \"mcdMemoryAllocated\": 2871, \n"
          + "                \"mcdMemoryReserved\": 2871, \n"
          + "                \"memoryFree\": 193156000, \n"
          + "                \"memoryTotal\": 3764372000.0, \n"
          + "                \"os\": \"i386-apple-darwin10.6.0\", \n"
          + "                \"ports\": {\n"
          + "                    \"direct\": 11210, \n"
          + "                    \"proxy\": 11211\n"
          + "                }, \n"
          + "                \"replication\": 1.0, \n"
          + "                \"status\": \"healthy\", \n"
          + "                \"uptime\": \"57\", \n"
          + "                \"version\": \"1.6.5.3_5_gb78249f\"\n"
          + "            }\n"
          + "        ], \n"
          + "        \"proxyPort\": 0, \n"
          + "        \"quota\": {\n"
          + "            \"ram\": 104857600, \n"
          + "            \"rawRAM\": 104857600\n"
          + "        }, \n"
          + "        \"replicaNumber\": 1, \n"
          + "        \"saslPassword\": \"\", \n"
          + "        \"stats\": {\n"
          + "            \"uri\": \"/pools/default/buckets/default/stats\"\n"
          + "        }, \n"
          + "        \"streamingUri\": \"/pools/default/bucketsStreaming/"
          + "default\", \n"
          + "        \"uri\": \"/pools/default/buckets/default\", \n"
          + "        \"vBucketServerMap\": {\n"
          + "            \"hashAlgorithm\": \"CRC\", \n"
          + "            \"numReplicas\": 1, \n"
          + "            \"serverList\": [\n"
          + "                \"127.0.0.1:11210\"\n" + "            ], \n"
          + "            \"vBucketMap\": [\n" + "                [\n"
          + "                    0, \n" + "                    -1\n"
          + "                ] \n" + "            ]\n" + "        }\n"
          + "    }\n" + "]\n";
