		setMaxDeltaDepth(rc.getInt("pack"
		setDeltaSearchWindowSize(rc.getInt(
				"pack"
		setDeltaSearchMemoryLimit(rc.getLong(
				"pack"
		setDeltaCacheSize(rc.getLong(
				"pack"
		setDeltaCacheLimit(rc.getInt(
				"pack"
		setCompressionLevel(rc.getInt("pack"
				rc.getInt("core"
		setIndexVersion(rc.getInt("pack"
		setBigFileThreshold(rc.getInt(
				"core"
		setThreads(rc.getInt("pack"
