		case BasicPackageImpl.PART__CONTRIBUTION_URI:
			return getContributionURI();
		case BasicPackageImpl.PART__OBJECT:
			return getObject();
		case BasicPackageImpl.PART__CONTEXT:
			return getContext();
		case BasicPackageImpl.PART__VARIABLES:
			return getVariables();
		case BasicPackageImpl.PART__PROPERTIES:
			if (coreType)
				return ((EMap.InternalMapView<String, String>) getProperties()).eMap();
			else
				return getProperties();
		case BasicPackageImpl.PART__LABEL:
			return getLabel();
		case BasicPackageImpl.PART__ICON_URI:
			return getIconURI();
		case BasicPackageImpl.PART__TOOLTIP:
			return getTooltip();
		case BasicPackageImpl.PART__LOCALIZED_LABEL:
			return getLocalizedLabel();
		case BasicPackageImpl.PART__LOCALIZED_TOOLTIP:
			return getLocalizedTooltip();
		case BasicPackageImpl.PART__HANDLERS:
			return getHandlers();
		case BasicPackageImpl.PART__DIRTY:
			return isDirty();
		case BasicPackageImpl.PART__BINDING_CONTEXTS:
			return getBindingContexts();
		case BasicPackageImpl.PART__MENUS:
			return getMenus();
		case BasicPackageImpl.PART__TOOLBAR:
			return getToolbar();
		case BasicPackageImpl.PART__CLOSEABLE:
			return isCloseable();
		case BasicPackageImpl.PART__DESCRIPTION:
			return getDescription();
		case BasicPackageImpl.PART__LOCALIZED_DESCRIPTION:
			return getLocalizedDescription();
		case BasicPackageImpl.PART__TRIM_BARS:
			return getTrimBars();
