import net.spy.memcached.ops.OperationStatus;
import net.spy.memcached.protocol.couchdb.DocsOperation.DocsCallback;
import net.spy.memcached.protocol.couchdb.DocsOperationImpl;
import net.spy.memcached.protocol.couchdb.HttpOperation;
import net.spy.memcached.protocol.couchdb.NoDocsOperation.NoDocsCallback;
import net.spy.memcached.protocol.couchdb.NoDocsOperationImpl;
import net.spy.memcached.protocol.couchdb.ReducedOperation.ReducedCallback;
import net.spy.memcached.protocol.couchdb.ReducedOperationImpl;
import net.spy.memcached.protocol.couchdb.RowError;
