
	String PROJECT_EXPLORER_RENAME_MODE = "PROJECT_EXPLORER_RENAME_MODE"; //$NON-NLS-1$

	String PROJECT_EXPLORER_RENAME_MODE_INLINE = "inline"; //$NON-NLS-1$

	String PROJECT_EXPLORER_RENAME_MODE_DIALOG = "dialog"; //$NON-NLS-1$
