  private static final String CONFIG_IN_ENVELOPE =
      "{"
          + "    \"authType\": \"sasl\", "
          + "    \"basicStats\": {"
          + "        \"diskUsed\": 0, "
          + "        \"hitRatio\": 0, "
          + "        \"itemCount\": 10001, "
          + "        \"memUsed\": 27007687, "
          + "        \"opsPerSec\": 0, "
          + "        \"quotaPercentUsed\": 10.061147436499596"
          + "    }, "
          + "    \"bucketType\": \"memcached\", "
          + "    \"flushCacheUri\": \"/pools/default/buckets/default/controller"
          + "/doFlush\", "
          + "    \"name\": \"default\", "
          + "    \"nodeLocator\": \"ketama\", "
          + "    \"nodes\": ["
          + "        {"
          + "            \"clusterCompatibility\": 1, "
          + "            \"clusterMembership\": \"active\", "
          + "            \"hostname\": \"127.0.0.1:8091\", "
          + "            \"mcdMemoryAllocated\": 2985, "
          + "            \"mcdMemoryReserved\": 2985, "
          + "            \"memoryFree\": 285800000, "
          + "            \"memoryTotal\": 3913584000.0, "
          + "            \"os\": \"i386-apple-darwin9.8.0\", "
          + "            \"ports\": {"
          + "                \"direct\": 11210, "
          + "                \"proxy\": 11211"
          + "            }, "
          + "            \"replication\": 1.0, "
          + "            \"status\": \"unhealthy\", "
          + "            \"uptime\": \"4204\", "
          + "            \"version\": \"1.6.5\""
          + "        }"
          + "    ], "
          + "    \"proxyPort\": 0, "
          + "    \"quota\": {"
          + "        \"ram\": 268435456, "
          + "        \"rawRAM\": 268435456"
          + "    }, "
          + "    \"replicaNumber\": 0, "
          + "    \"saslPassword\": \"\", "
          + "    \"stats\": {"
          + "        \"uri\": \"/pools/default/buckets/default/stats\""
          + "    }, "
          + "    \"streamingUri\": \"/pools/default/bucketsStreaming/default"
          + "\", "
          + "    \"uri\": \"/pools/default/buckets/default\"" + "}";
