		g1 = createEGenericType(this.getFrame());
		g2 = createEGenericType(this.getDialogElement());
		g1.getETypeArguments().add(g2);
		dialogEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(this.getFrame());
		g2 = createEGenericType(this.getWizardElement());
		g1.getETypeArguments().add(g2);
		wizardDialogEClass.getEGenericSuperTypes().add(g1);
		dialogElementEClass.getESuperTypes().add(theUiPackage.getUIElement());
		wizardElementEClass.getESuperTypes().add(theUiPackage.getUIElement());
		g1 = createEGenericType(theUiPackage.getElementContainer());
		g2 = createEGenericType(frameEClass_T);
		g1.getETypeArguments().add(g2);
		frameEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(theUiPackage.getUILabel());
		frameEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(theUiPackage.getContext());
		frameEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(theCommandsPackage.getHandlerContainer());
		frameEClass.getEGenericSuperTypes().add(g1);
		g1 = createEGenericType(theCommandsPackage.getBindings());
		frameEClass.getEGenericSuperTypes().add(g1);
