		setMinBytesForObjSizeIndex(rc.getInt(CONFIG_PACK_SECTION
				CONFIG_KEY_MIN_BYTES_OBJ_SIZE_INDEX
				DEFAULT_MIN_BYTES_FOR_OBJ_SIZE_INDEX));
		setPreserveOldPacks(rc.getBoolean(CONFIG_PACK_SECTION
				CONFIG_KEY_PRESERVE_OLD_PACKS
		setPrunePreserved(rc.getBoolean(CONFIG_PACK_SECTION
				CONFIG_KEY_PRUNE_PRESERVED
