		 * - fRootElement
		 * |+element_0
		 * |-element_1
		 * ||+element_1_0
		 * ||+element_1_1
		 * ||+element_1_2
		 * ||+element_1_3
		 * ||+element_1_4
		 * ||+element_1_5
		 * ||+element_1_6
		 * ||+element_1_7
		 * ||+element_1_8
		 * ||+element_1_9
		 * ||+element_2
		 * ||+element_2_1
		 * ||+element_2_1_2
		 * |-element_2
		 * ||+element_2_0
		 * ||-element_2_1
		 * |||+element_2_1_0
		 * |||+element_2_1_1
		 * |||+element_2_1_2
		 * |||+element_2_1_3
		 * |||+element_2_1_4
		 * |||+element_2_1_5
		 * |||+element_2_1_6
		 * |||+element_2_1_7
		 * |||+element_2_1_8
		 * |||+element_2_1_9
		 * ||+element_2_2
		 * ||+element_2_3
		 * ||+element_2_4
		 * ||+element_2_5
		 * ||+element_2_6
		 * ||+element_2_7
		 * ||+element_2_8
		 * ||+element_2_9
		 * |+element_3
		 * |+element_4
		 * |+element_5
		 * |+element_6
		 * |+element_7
		 * |+element_8
		 * |+element_9
