		Display display = PlatformUI.getWorkbench().getDisplay();
		Shell shell = new Shell(display);
		shell.setSize(100, 300);
		shell.setLayout(new FillLayout());
		Composite inner = new Composite(shell, SWT.V_SCROLL);
		TableWrapLayout tableWrapLayout = new TableWrapLayout();
		tableWrapLayout.numColumns = 2;
		inner.setLayout(tableWrapLayout);
		Label l1 = new Label(inner, SWT.WRAP);
		l1.setText(A10);
		Label l2 = new Label(inner, SWT.WRAP);
		l2.setText(A20);
		Label l3 = new Label(inner, SWT.WRAP);
		l3.setText(A40);
		Label l4 = new Label(inner, SWT.WRAP);
		l4.setText(A80);
		shell.layout();
		assertTrue(l1.getSize().x < l2.getSize().x);
		assertTrue(l1.getSize().y < l3.getSize().y);
		assertTrue(l1.getSize().x < l4.getSize().x);
		assertTrue(l2.getSize().y < l3.getSize().y);
		assertTrue("Label is too wide for layout ", l1.getSize().x + l2.getSize().x <= 100);
		assertTrue("Labels overlap", l2.getBounds().x >= l1.getBounds().x + l1.getBounds().width);
		assertTrue("Labels overlap", l3.getBounds().y >= l1.getBounds().y + l1.getBounds().height);
		assertTrue("Labels overlap", l4.getBounds().x >= l3.getBounds().x + l3.getBounds().width);
		assertTrue("Labels overlap", l4.getBounds().y >= l2.getBounds().y + l2.getBounds().height);
		shell.dispose();
