		case BasicPackageImpl.PART_DESCRIPTOR__LABEL:
			return getLabel();
		case BasicPackageImpl.PART_DESCRIPTOR__ICON_URI:
			return getIconURI();
		case BasicPackageImpl.PART_DESCRIPTOR__TOOLTIP:
			return getTooltip();
		case BasicPackageImpl.PART_DESCRIPTOR__LOCALIZED_LABEL:
			return getLocalizedLabel();
		case BasicPackageImpl.PART_DESCRIPTOR__LOCALIZED_TOOLTIP:
			return getLocalizedTooltip();
		case BasicPackageImpl.PART_DESCRIPTOR__HANDLERS:
			return getHandlers();
		case BasicPackageImpl.PART_DESCRIPTOR__BINDING_CONTEXTS:
			return getBindingContexts();
		case BasicPackageImpl.PART_DESCRIPTOR__ALLOW_MULTIPLE:
			return isAllowMultiple();
		case BasicPackageImpl.PART_DESCRIPTOR__CATEGORY:
			return getCategory();
		case BasicPackageImpl.PART_DESCRIPTOR__MENUS:
			return getMenus();
		case BasicPackageImpl.PART_DESCRIPTOR__TOOLBAR:
			return getToolbar();
		case BasicPackageImpl.PART_DESCRIPTOR__CLOSEABLE:
			return isCloseable();
		case BasicPackageImpl.PART_DESCRIPTOR__DIRTYABLE:
			return isDirtyable();
		case BasicPackageImpl.PART_DESCRIPTOR__CONTRIBUTION_URI:
			return getContributionURI();
		case BasicPackageImpl.PART_DESCRIPTOR__DESCRIPTION:
			return getDescription();
		case BasicPackageImpl.PART_DESCRIPTOR__LOCALIZED_DESCRIPTION:
			return getLocalizedDescription();
		case BasicPackageImpl.PART_DESCRIPTOR__VARIABLES:
			return getVariables();
		case BasicPackageImpl.PART_DESCRIPTOR__PROPERTIES:
			if (coreType) return ((EMap.InternalMapView<String, String>)getProperties()).eMap();
			else return getProperties();
		case BasicPackageImpl.PART_DESCRIPTOR__TRIM_BARS:
			return getTrimBars();
