	static final int BUTTON_ON_ANY = 1;

	static final int BUTTON_ON_ANY_IN_SAME_CONTAINER = 1 << 1;

	static final int BUTTON_ON_SELECTED_AND_CHILDREN = 1 << 2;
	static final int BUTTON_ON_SELECTED_ONLY = 1 << 3;
	static final int BUTTON_ON_WORKING_SET = 1 << 4;

	static final int ALL_BUTTONS_ENABLED = BUTTON_ON_ANY | BUTTON_ON_ANY_IN_SAME_CONTAINER
			| BUTTON_ON_SELECTED_AND_CHILDREN | BUTTON_ON_SELECTED_ONLY | BUTTON_ON_WORKING_SET;

