		b.append("
				.append(getBitmapContiguousCommitCount());
		b.append("
				.append(getBitmapRecentCommitCount());
		b.append("
				.append(getBitmapRecentCommitSpan());
		b.append("
				.append(getBitmapDistantCommitSpan());
		b.append("
				.append(getBitmapExcessiveBranchCount());
		b.append("
				.append(getBitmapInactiveBranchAgeInDays());
