		setReuseObjects(
				rc.getBoolean("pack"
		setDeltaCompress(
				rc.getBoolean("pack"
		setCutDeltaChains(
				rc.getBoolean("pack"
		setBuildBitmaps(
				rc.getBoolean("pack"
		setBitmapContiguousCommitCount(
				rc.getInt("pack"
						getBitmapContiguousCommitCount()));
		setBitmapRecentCommitCount(rc.getInt("pack"
				getBitmapRecentCommitCount()));
		setBitmapRecentCommitSpan(rc.getInt("pack"
				getBitmapRecentCommitSpan()));
		setBitmapDistantCommitSpan(rc.getInt("pack"
				getBitmapDistantCommitSpan()));
		setBitmapExcessiveBranchCount(rc.getInt("pack"
				"bitmapexcessivebranchcount"
		setBitmapInactiveBranchAgeInDays(
				rc.getInt("pack"
						getBitmapInactiveBranchAgeInDays()));
