		setReuseDeltas(rc.getBoolean(CONFIG_PACK_SECTION
				CONFIG_KEY_REUSE_DELTAS
		setReuseObjects(rc.getBoolean(CONFIG_PACK_SECTION
				CONFIG_KEY_REUSE_OBJECTS
		setDeltaCompress(rc.getBoolean(CONFIG_PACK_SECTION
				CONFIG_KEY_DELTA_COMPRESSION
		setCutDeltaChains(rc.getBoolean(CONFIG_PACK_SECTION
				CONFIG_KEY_CUT_DELTACHAINS
		setSinglePack(rc.getBoolean(CONFIG_PACK_SECTION
				CONFIG_KEY_SINGLE_PACK
				getSinglePack()));
		setBuildBitmaps(rc.getBoolean(CONFIG_PACK_SECTION
				CONFIG_KEY_BUILD_BITMAPS
		setBitmapContiguousCommitCount(rc.getInt(CONFIG_PACK_SECTION
				CONFIG_KEY_BITMAP_CONTIGUOUS_COMMIT_COUNT
				getBitmapContiguousCommitCount()));
		setBitmapRecentCommitCount(rc.getInt(CONFIG_PACK_SECTION
				CONFIG_KEY_BITMAP_RECENT_COMMIT_COUNT
