		setMaxDeltaDepth(rc.getInt(CONFIG_PACK_SECTION
				getMaxDeltaDepth()));
		setDeltaSearchWindowSize(rc.getInt(CONFIG_PACK_SECTION
				CONFIG_KEY_WINDOW
		setDeltaSearchMemoryLimit(rc.getLong(CONFIG_PACK_SECTION
				CONFIG_KEY_WINDOW_MEMORY
		setDeltaCacheSize(rc.getLong(CONFIG_PACK_SECTION
				CONFIG_KEY_DELTA_CACHE_SIZE
		setDeltaCacheLimit(rc.getInt(CONFIG_PACK_SECTION
				CONFIG_KEY_DELTA_CACHE_LIMIT
		setCompressionLevel(rc.getInt(CONFIG_PACK_SECTION
				CONFIG_KEY_COMPRESSION
						CONFIG_KEY_COMPRESSION
		setIndexVersion(rc.getInt(CONFIG_PACK_SECTION
				CONFIG_KEY_INDEXVERSION
				getIndexVersion()));
		setBigFileThreshold(rc.getInt(CONFIG_CORE_SECTION
				CONFIG_KEY_BIGFILE_THRESHOLD
		setThreads(rc.getInt(CONFIG_PACK_SECTION
				getThreads()));
