	public static final int IMPERATIVE_EXPRESSION = 11;

	public static final int IMPERATIVE_EXPRESSION__ELEMENT_ID = EXPRESSION__ELEMENT_ID;

	public static final int IMPERATIVE_EXPRESSION__PERSISTED_STATE = EXPRESSION__PERSISTED_STATE;

	public static final int IMPERATIVE_EXPRESSION__TAGS = EXPRESSION__TAGS;

	public static final int IMPERATIVE_EXPRESSION__CONTRIBUTOR_URI = EXPRESSION__CONTRIBUTOR_URI;

	public static final int IMPERATIVE_EXPRESSION__TRANSIENT_DATA = EXPRESSION__TRANSIENT_DATA;

	public static final int IMPERATIVE_EXPRESSION__CONTRIBUTION_URI = EXPRESSION_FEATURE_COUNT + 0;

	public static final int IMPERATIVE_EXPRESSION__OBJECT = EXPRESSION_FEATURE_COUNT + 1;

	public static final int IMPERATIVE_EXPRESSION__TRACKING = EXPRESSION_FEATURE_COUNT + 2;

	public static final int IMPERATIVE_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

	public static final int IMPERATIVE_EXPRESSION_OPERATION_COUNT = EXPRESSION_OPERATION_COUNT + 0;

