@SuiteClasses({ AbstractObservableListTest.class, AbstractObservableMapTest.class, AbstractObservableTest.class,
		AbstractObservableValueTest.class, AbstractStringToNumberValidatorTest.class, AbstractVetoableValueTest.class,
		AggregateValidationStatusTest.class, AnonymousBeanValuePropertyTest.class, AnonymousPojoValuePropertyTest.class,
		BeanObservableListDecoratorTest.class, BeanObservableListDecoratorTest.class,
		BeanObservableSetDecoratorTest.class, BeanObservableValueDecoratorTest.class, BeanPropertiesTest.class,
		BeanPropertyHelperTest.class, BeanPropertyListenerSupportTest.class, BeanPropertyListenerTest.class,
		BeansObservablesTest.class, BeanValuePropertyTest.class, BidiObservableMapTest.class, BindingMessagesTest.class,
		BindingScenariosTestSuite.class, BindingStatusTest.class, BindingTest.class, BindingTestSuiteJunit3.class,
		ButtonObservableValueTest.class, CComboObservableValueSelectionTest.class, CComboObservableValueTest.class,
		CComboObservableValueTextTest.class, CComboSingleSelectionObservableValueTest.class,
		CComboSingleSelectionObservableValueTest.class, ChangeSupportTest.class,
		CheckableCheckedElementsObservableSetTest.class, CLabelObservableValueTest.class,
		ComboObservableValueSelectionTest.class, ComboObservableValueTest.class, ComboObservableValueTextTest.class,
		ComboSingleSelectionObservableValueTest.class, CompositeMapTest.class, ComputedListTest.class,
		ComputedObservableMapTest.class, ComputedSetTest.class, ComputedValueTest.class,
		ConstantObservableValueTest.class, ControlObservableValueTest.class, ConverterValuePropertyTest.class,
		DatabindingContextTest.class, DateAndTimeObservableValueTest.class, DateConversionSupportTest.class,
		DateTimeCalendarObservableValueTest.class, DateTimeDateObservableValueTest.class,
		DateTimeSelectionPropertyTest.class, DateTimeTimeObservableValueTest.class, DecoratingObservableTest.class,
		DelayedObservableValueTest.class, DetailObservableListTest.class, DetailObservableMapTest.class,
		DetailObservableSetTest.class, DetailObservableValueTest.class, DifferentRealmsBindingTest.class,
		Diffs_ListDiffTests.class, DiffsTest.class, DuplexingObservableValueTest.class, EditMaskLexerAndTokenTest.class,
		EditMaskParserTest.class, GroupObservableValueTest.class, IdentityConverterTest.class, IdentityMapTest.class,
		IdentitySetTest.class, IntegerToStringConverterTest.class, JavaBeanObservableArrayBasedListTest.class,
		JavaBeanObservableArrayBasedSetTest.class, JavaBeanObservableListTest.class, JavaBeanObservableMapTest.class,
		JavaBeanObservableSetTest.class, JavaBeanObservableValueTest.class, JavaBeanPropertyObservableMapTest.class,
		LabelObservableValueTest.class, ListBindingTest.class, ListDetailValueObservableListTest.class,
		ListDiffTest.class, ListDiffVisitorTest.class, ListSimpleValueObservableListTest.class,
		ListSingleSelectionObservableValueTest.class, MapDetailValueObservableMapTest.class,
		MapEntryObservableValueTest.class, MapSimpleValueObservableMapTest.class, MultiListTest.class,
		MultiValidatorTest.class, NumberToBigDecimalTest.class, NumberToBigIntegerConverterTest.class,
		NumberToByteConverterTest.class, NumberToByteValidatorTest.class, NumberToDoubleConverterTest.class,
		NumberToDoubleValidatorTest.class, NumberToFloatConverterTest.class, NumberToFloatValidatorTest.class,
		NumberToIntegerConverterTest.class, NumberToIntegerValidatorTest.class, NumberToLongConverterTest.class,
		NumberToLongValidatorTest.class, NumberToShortConverterTest.class, NumberToShortValidatorTest.class,
		NumberToStringConverterTest.class, NumberToUnboundedNumberValidatorTest.class,
		ObjectToPrimitiveValidatorTest.class, ObservableCollectionContentProviderTest.class,
		ObservableCollectionTreeContentProviderTest.class, ObservableListContentProviderTest.class,
		ObservableListTest.class, ObservableListTreeContentProviderTest.class, ObservableMapLabelProviderTest.class,
		ObservableMapTest.class, ObservableSetContentProviderTest.class, ObservableSetTreeContentProviderTest.class,
		ObservablesManagerTest.class, ObservablesTest.class, ObservableTrackerTest.class,
		ObservableValueEditingSupportTest.class, PojoObservablesTest.class, PojoPropertiesTest.class, PolicyTest.class,
		PreferencePageSupportTest.class, QueueTest.class, RealmTest.class, ScaleObservableValueMaxTest.class,
		ScaleObservableValueMinTest.class, ScaleObservableValueSelectionTest.class,
		SelectionProviderMultiSelectionObservableListTest.class,
		SelectionProviderSingleSelectionObservableValueTest.class, SetDetailValueObservableMapTest.class,
		SetOnlyJavaBeanTest.class, SetSimpleValueObservableMapTest.class, ShellObservableValueTest.class,
		SideEffectTest.class, SpinnerObservableValueMaxTest.class, SpinnerObservableValueMinTest.class,
		SpinnerObservableValueSelectionTest.class, SpinnerObservableValueTest.class, StatusToStringConverterTest.class,
		StringToBooleanConverterTest.class, StringToByteConverterTest.class, StringToByteValidatorTest.class,
		StringToCharacterConverterTest.class, StringToCharacterValidatorTest.class, StringToDoubleValidatorTest.class,
		StringToFloatValidatorTest.class, StringToIntegerValidatorTest.class, StringToLongValidatorTest.class,
		StringToNumberConverterTest.class, StringToNumberParserByteTest.class, StringToNumberParserDoubleTest.class,
		StringToNumberParserFloatTest.class, StringToNumberParserIntegerTest.class, StringToNumberParserLongTest.class,
		StringToNumberParserShortTest.class, StringToNumberParserTest.class, StringToShortConverterTest.class,
		StringToShortValidatorTest.class, StyledTextObservableValueFocusOutTest.class,
		StyledTextObservableValueTest.class, SWTDelayedObservableValueDecoratorTest.class, SWTObservablesTest.class,
		TableObservableValueTest.class, TableSingleSelectionObservableValueTest.class,
		TextEditableObservableValueTest.class, TextObservableValueFocusOutTest.class, TextObservableValueTest.class,
		UnmodifiableObservableListTest.class, UnmodifiableObservableSetTest.class,
		UnmodifiableObservableValueTest.class, UpdateListStrategyTest.class, UpdateSetStrategyTest.class,
		UpdateStrategyTest.class, UpdateValueStrategyTest.class, ValidatedObservableValueTest.class,
		ValidationStatusTest.class, ValueBindingTest.class, ViewerElementMapTest.class, ViewerElementSetTest.class,
		ViewerElementWrapperTest.class, ViewerInputObservableValueTest.class, ViewersObservablesTest.class,
		ViewerSupportTest.class, WidgetObservableThreadTest.class, WidgetPropertiesTest.class,
		WizardPageSupportTest.class, WritableListTest.class, WritableMapTest.class, WritableSetTest.class,
		WritableValueTest.class })
