
package org.eclipse.ui.internal.handlers;

import java.util.HashMap;
import java.util.Map;

import org.eclipse.ui.internal.registry.IWorkbenchRegistryConstants;

public final class ActionCommandMappingService implements
		IActionCommandMappingService {

	private final Map mapping = new HashMap();

	@Override
	public final String getCommandId(final String actionId) {
		if (actionId == null) {
			throw new NullPointerException(
					"Cannot get the command identifier for a null action id"); //$NON-NLS-1$
		}

		return (String) mapping.get(actionId);
	}

	@Override
	public final void map(final String actionId, final String commandId) {
		if (actionId == null) {
			throw new NullPointerException("The action id cannot be null"); //$NON-NLS-1$
		}

		if (commandId == null) {
			throw new NullPointerException("The command id cannot be null"); //$NON-NLS-1$
		}

		mapping.put(actionId, commandId);
	}

	@Override
	public final String getGeneratedCommandId(String targetId, String actionId) {
		return IWorkbenchRegistryConstants.AUTOGENERATED_PREFIX + targetId
				+ '/' + actionId;
	}
}
