         label="%theme.winvistaClassic"
         os="win32"
         os_version="6.0">
   </theme>
   <theme
         basestylesheeturi="css/e4_classic_win7.css"
         id="org.eclipse.e4.ui.css.theme.e4_classic"
         label="%theme.win7Classic"
         os="win32"
         os_version="6.1">
   </theme>
   <theme
         basestylesheeturi="css/e4_classic_win7.css"
         id="org.eclipse.e4.ui.css.theme.e4_classic"
         label="%theme.win8Classic"
         os="win32"
         os_version="6.2">
   </theme>
   <theme
         basestylesheeturi="css/e4_classic_win7.css"
         id="org.eclipse.e4.ui.css.theme.e4_classic"
         label="%theme.win8.1Classic"
