	public void suppressed_testWrappingPoint() {
		Display display = PlatformUI.getWorkbench().getDisplay();
		Shell shell = new Shell(display);
		shell.setSize(300, 300);
		shell.setLayout(new FillLayout());
		Composite inner = new Composite(shell, SWT.V_SCROLL);
		TableWrapLayout tableWrapLayout = new TableWrapLayout();
		tableWrapLayout.leftMargin = 0;
		tableWrapLayout.rightMargin = 0;
		inner.setLayout(tableWrapLayout);
		Label l1 = new Label(inner, SWT.WRAP);
		l1.setText(A10);
		shell.layout();
		int originalWidth = l1.getSize().x;
		int originalHeight = l1.getSize().y;
		shell.setSize(originalWidth, 300);
		shell.layout();
		assertEquals(l1.getSize().y, originalHeight);
		shell.setSize(originalWidth / 2, 300);
		shell.layout();
