
	String RESOURCE_RENAME_MODE = "RESOURCE_RENAME_MODE"; //$NON-NLS-1$

	String RESOURCE_RENAME_MODE_INLINE = "inline"; //$NON-NLS-1$

	String RESOURCE_RENAME_MODE_DIALOG = "dialog"; //$NON-NLS-1$
