            queryErrorObservable,
            queryRowObservable,
            querySignatureObservable,
            queryStatusObservable,
            queryInfoObservable,
            queryProfileInfoObservable,
