				"On branch master"
						"Changes to be committed:"
						""
						"\tdeleted:    stagedDeleted"
						"\tmodified:   stagedModified"
						"\tnew file:   stagedNew"
						""
						"Changes not staged for commit:"
						""
						"\tdeleted:    trackedDeleted"
						"\tmodified:   trackedModified"
						""
						"Untracked files:"
						""
						"\tuntracked"
