				"On branch master"
						"Untracked files:"
						""
						"\tstagedDeleted"
						"\tstagedModified"
						"\tstagedNew"
						"\ttracked"
						"\ttrackedDeleted"
						"\ttrackedModified"
						"\tuntracked"
