            os_version="6.1">
      </theme>
      <theme
            basestylesheeturi="css/e4_default_win7.css"
            id="org.eclipse.e4.ui.css.theme.e4_default"
            label="%theme.win8"
            os="win32"
            os_version="6.2">
      </theme>
      <theme
            basestylesheeturi="css/e4_default_win7.css"
            id="org.eclipse.e4.ui.css.theme.e4_default"
            label="%theme.win8.1"
            os="win32"
            os_version="6.3">
