import org.eclipse.egit.core.internal.project.RepositoryMapping;
import org.eclipse.egit.core.internal.synchronize.GitBaseResourceVariantTree;
import org.eclipse.egit.core.internal.synchronize.GitRemoteResource;
import org.eclipse.egit.core.internal.synchronize.GitRemoteResourceVariantTree;
import org.eclipse.egit.core.internal.synchronize.GitResourceVariantTreeSubscriber;
import org.eclipse.egit.core.internal.synchronize.dto.GitSynchronizeData;
import org.eclipse.egit.core.internal.synchronize.dto.GitSynchronizeDataSet;
import org.eclipse.egit.core.internal.test.GitTestCase;
import org.eclipse.egit.core.internal.test.TestRepository;
