	/***/ public String DIRCChecksumMismatch;
	/***/ public String DIRCExtensionIsTooLargeAt;
	/***/ public String DIRCExtensionNotSupportedByThisVersion;
	/***/ public String DIRCHasTooManyEntries;
	/***/ public String DIRCUnrecognizedExtendedFlags;
	/***/ public String JRELacksMD5Implementation;
	/***/ public String URINotSupported;
	/***/ public String URLNotFound;
	/***/ public String aNewObjectIdIsRequired;
