java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @730c14f)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @3355dbf6)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @4fd3ed67)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @288196cc)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @3f9fbc68)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @4407b1b8)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @1080d265)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @60198c7c)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @4407b1b8)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @7e06b3cb)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @331f3583)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
