				.append("<manifest>")
				.append("<remote name=\"remote1\" fetch=\".\" />")
				.append("<default revision=\"master\" remote=\"remote1\" />")
				.append("<project path=\"foo\" name=\"")
				.append("foo")
				.append("\" groups=\"a
				.append("<project path=\"bar\" name=\"")
				.append("bar")
				.append("\" groups=\"notdefault\" />")
				.append("<project path=\"foo/a\" name=\"")
				.append("a")
				.append("\" groups=\"a\" />")
				.append("<project path=\"b\" name=\"")
				.append("b")
				.append("\" groups=\"b\" />")
				.append("</manifest>");
