java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @56f9473a)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @1d197565)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @3a412fd)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @557458f6)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @47719777)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @64b03ee6)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @5d8b8d27)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @27a8170d)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @5fd02a5c)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @4c2021d2)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @430b8a74)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @7a441948)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @284ef0a1)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @25589484)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @246f3e6e)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @1a696b7b)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @2e26d349)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @389149ea)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @288196cc)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @efcba8)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @2632fa66)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @2694d587)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @5583953)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @2ef9f032)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @25fbe503)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @1080d265)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @730c14f)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @3355dbf6)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @4fd3ed67)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @288196cc)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @3f9fbc68)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @4407b1b8)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @1080d265)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @60198c7c)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @4407b1b8)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @7e06b3cb)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Binary cannot be cast to class org.openrewrite.java.tree.J$MethodInvocation (org.openrewrite.java.tree.J$Binary and org.openrewrite.java.tree.J$MethodInvocation are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @331f3583)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:76)
  org.openrewrite.java.testing.cleanup.AssertTrueEqualsToAssertEquals$1.visitMethodInvocation(AssertTrueEqualsToAssertEquals.java:51)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3470)
  org.openrewrite.java.tree.J.accept(J.java:60)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:248)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:327)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1226)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:367)
